
name: Open API Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: swagger-cli
        uses: vaibhav-jain/spectral-action/@v2.6
        with:
          file_path: docs/openapi.yaml