
name: Open API Check

on:
  pull_request:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: check
    steps:
      # first checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # then use redoc-cli-github-action to generate your HTML bundle
      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle docs/openapi.yml'